services:
  - type: web
    name: hackerrrr-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    plan: free
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: False
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: remote_script_server
    healthCheckPath: /api/health

  - type: web
    name: hackerrrr-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false

